name: Deploy Dashboard to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Dashboard
        run: |
          echo "VITE_API_URL=https://replay.suhanisagar.dev/api" > .env.production
          npm run build

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: "13.61.174.212"
          USER: "ubuntu"
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          
          # Delete old files and upload new ones
          ssh -i private_key.pem $USER@$HOST "rm -rf /var/www/replay/*"
          scp -i private_key.pem -r dist/* $USER@$HOST:/var/www/replay/
